# SPDX-FileCopyrightText: 2026 Jacques Supcik <jacques.supci@hes-so.ch>
#
# SPDX-License-Identifier: MIT
---
- name: Validate system requirements
  assert:
    that:
      - ansible_facts["system"] | lower == 'linux'
      - ansible_facts["service_mgr"] == 'systemd'
    fail_msg: 'This role requires a Linux system with systemd as the service manager.'

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  loop:
    - ffmpeg

- name: Install systemd service unit
  ansible.builtin.template:
    src: screen-streaming.service.j2
    dest: /etc/systemd/system/screen-streaming.service
    mode: '0644'
  when:
    - ansible_facts["system"] | lower == 'linux'
    - ansible_facts["service_mgr"] == 'systemd'
  notify:
    - Reload systemd
    - Restart screen-streaming

- name: Ensure screen-streaming service is enabled and started
  ansible.builtin.systemd:
    name: screen-streaming
    enabled: '{{ screen_streaming_service_enabled }} | bool'
    state: '{{ "started" if screen_streaming_service_enabled | bool else "stopped" }}'
    daemon_reload: true
  when:
    - ansible_facts["system"] | lower == 'linux'
    - ansible_facts["service_mgr"] == 'systemd'
