# SPDX-FileCopyrightText: 2026 Jacques Supcik <jacques.supci@hes-so.ch>
#
# SPDX-License-Identifier: MIT
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_facts["system"] | lower == 'linux'
    - ansible_facts["service_mgr"] == 'systemd'

- name: Restart screen-streaming
  ansible.builtin.systemd:
    name: screen-streaming
    state: restarted
    daemon_reload: true
  when:
    - ansible_facts["system"] | lower == 'linux'
    - ansible_facts["service_mgr"] == 'systemd'
    - screen_streaming_service_enabled | bool
  # Prevent errors if the systemd service file hasn't been created yet
  ignore_errors: true
